# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy manifest and config first
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install all deps and build
RUN npm ci
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app
# Install production deps without running build scripts
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

# Copy built artifacts
COPY --from=builder /app/dist ./dist
COPY client-config.json ./

ENTRYPOINT ["node", "dist/index.js"]
